### ISSUE TITLE
Can't get liquibase:diffDatabaseToChangeLog to work in ant

### ISSUE THREAD

**Issue by vizor21** [liquibase/liquibase-hibernate#114]
I cannot get this task to work in ant.  Someone else on the project got it working from the command line, so I'm not sure if I'm doing something wrong or the ant version is just broken.  I have tried dozens of variations but always the same error:

BUILD FAILED
C:\Production\jboss_emr_eap\g2\dbautomation.xml:54: JDBC driver is required.
    at liquibase.integration.ant.type.DatabaseType.validateParameters(DatabaseType.java:133)
    at liquibase.integration.ant.type.DatabaseType.createDatabase(DatabaseType.java:51)
    at liquibase.integration.ant.BaseLiquibaseTask.createDatabaseFromType(BaseLiquibaseTask.java:96)
    at liquibase.integration.ant.AbstractDatabaseDiffTask.getDiffResult(AbstractDatabaseDiffTask.java:24)
    at liquibase.integration.ant.DiffDatabaseToChangeLogTask.executeWithLiquibaseClassloader(DiffDatabaseToChangeLogTask.java:44)
    at liquibase.integration.ant.BaseLiquibaseTask.execute(BaseLiquibaseTask.java:81)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:392)
    at org.apache.tools.ant.Target.performTasks(Target.java:413)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:32)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
    at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:424)
    at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:138)

**My ant build file:**

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns:liquibase="antlib:liquibase.integration.ant" basedir="." name="liquibase">
    <property name="PROP_FILE_PATH" value="${basedir}"/>
    <loadproperties srcFile="${PROP_FILE_PATH}/liquibase.properties"/>
    <path id="liquibase.libraryclasspath">
        <pathelement location="buildLibs/dom4j-1.6.1.jar" />
        <pathelement location="buildLibs/hibernate-common-annotations-4.0.1.Final-redhat-2.jar" />
        <pathelement location="buildLibs/hibernate-core-4.2.7.SP1-redhat-3.jar" />
        <pathelement location="buildLibs/hibernate-entitymanager-4.2.7.SP1-redhat-3.jar" />
        <pathelement location="buildLibs/hibernate-envers-4.2.7.SP1-redhat-3.jar" />
        <pathelement location="buildLibs/hibernate-validator-4.3.1.Final-redhat-1.jar" />
        <pathelement location="buildLibs/ironjacamar-jdbc-1.0.23.Final-redhat-1.jar" />
        <pathelement location="buildLibs/javassist-3.9.0.GA.jar" />
        <pathelement location="buildLibs/liquibase-hibernate4.2-3.5.jar" />
        <pathelement location="buildLibs/liquibase.jar" />
        <pathelement location="buildLibs/ojdbc6.jar" />
        <pathelement location="buildLibs/requestfactory-apt.jar" />
        <pathelement location="buildLibs/snakeyaml-1.13.jar" />
        <pathelement location="src/META-INF" />
    </path>
    <path id="mypath.classpath">
        <path refid="liquibase.libraryclasspath"/>
    </path>
    <!-- Reference the ant-liquibase integration tasks -->
    <taskdef resource="liquibase/integration/ant/antlib.xml" uri="antlib:liquibase.integration.ant">
        <classpath refid="liquibase.libraryclasspath"/>
    </taskdef>
    <!-- Define the database connection -->
    <liquibase:database id="my-database" 
        driver="${liquibase.database.driver}"
        url="${liquibase.database.url}" 
        user="${liquibase.database.username}" 
        password="${liquibase.database.password}" >
    </liquibase:database>
    <target name="diff-against-hibernate">
        <liquibase:diffDatabaseToChangeLog
                referenceurl="${liquibase.persistence.unit}"
                databaseref="my-database" 
                classpathref="mypath.classpath"
                diffTypes="tables,columns,views"> 
            <txt outputfile="hibernate-dff-test.xml"/>
        </liquibase:diffDatabaseToChangeLog>
    </target>
</project>
```

**liquibase.properties:**
liquibase.database.username=xxx
liquibase.database.password=xxx
liquibase.database.driver=oracle.jdbc.OracleDriver
liquibase.database.url=jdbc:oracle:thin:@XXXX
liquibase.persistence.unit=hibernate:ejb3:emrEJB?dialect=org.hibernate.dialect.OracleDialect

**The beginning of persistence.xml:**

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd" version="2.1">
    <persistence-unit name="emrEJB" transaction-type="JTA">
        <provider>org.hibernate.ejb.HibernatePersistence</provider>
                <jta-data-source>java:/emrDS</jta-data-source>
```

Other liquibase tasks such as liquibase:generateChangeLog (which uses the same classpathref) work perfectly.  The oracle jar mentioned above definitely contains the oracle driver.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-441) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Hi - seems this has been fixed in liquibase-core some years ago. Please reopen the issue if it still persists.
