### ISSUE TITLE
java.lang.NoSuchMethodError with liquibase 3.5

### ISSUE THREAD

**Issue by JimRichards22** [liquibase/liquibase-hibernate#117]
When using the latest version with liquibase 3.5 I get `java.lang.NoSuchMethodError: liquibase.structure.core.ForeignKey.addForeignKeyColumn`. This doesn't occur with liquibase 3.4.2. 

It's weird because in https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/structure/core/ForeignKey.java the method exists with the same signature

    public ForeignKey addForeignKeyColumn(Column foreignKeyColumn) {
        if (foreignKeyColumn.getAttribute("relation", Object.class) == null) {
            foreignKeyColumn.setRelation(getForeignKeyTable());
        }
        getAttribute("foreignKeyColumns", List.class).add(foreignKeyColumn);

        return this;
    }

This is the stacktrace

    Unexpected error running Liquibase: liquibase.structure.core.ForeignKey.addForeignKeyColumn(Lliquibase/structure/core/Column;)V

    SEVERE 30/04/16 9:44 PM: liquibase: liquibase.structure.core.ForeignKey.addForeignKeyColumn(Lliquibase/structure/core/Column;)V
    java.lang.NoSuchMethodError: liquibase.structure.core.ForeignKey.addForeignKeyColumn(Lliquibase/structure/core/Column;)V
	at liquibase.ext.hibernate.snapshot.ForeignKeySnapshotGenerator.addTo(ForeignKeySnapshotGenerator.java:54)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:80)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:244)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:349)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:371)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:291)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:265)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:78)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:51)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:28)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:150)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:139)
	at liquibase.command.DiffCommand.createReferenceSnapshot(DiffCommand.java:219)
	at liquibase.command.DiffCommand.createDiffResult(DiffCommand.java:141)
	at liquibase.command.DiffToChangeLogCommand.run(DiffToChangeLogCommand.java:51)
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:231)
	at liquibase.integration.commandline.Main.doMigration(Main.java:992)
	at liquibase.integration.commandline.Main.run(Main.java:184)
	at liquibase.integration.commandline.Main.main(Main.java:103)

**Comment by FlixBus** [comment]
We had the same problem here, had to revert to Liquibase 3.4.2. It doesn't look like this extension is actively in development anymore (which is a shame).

**Comment by JimRichards22** [comment]
Well, then. What needs to be done to make it active again?

**Comment by langecode** [comment]
Yeah that is really a shame - also could be nice with a Hibernate5 based version.

**Comment by nvoxland** [comment]
The liquibase-hibernate 3.6 release will support Liquibase 3.5 and fix this issue.

**Comment by ChanningMorris** [comment]
Just ran into this issue myself - is 3.6 still planning on being released soon?

**Comment by nvoxland** [comment]
Hopefully soon. I have one last url pattern to get working and then some testing. Taking longer than I hoped, but also working on the Liquibase 3.5.2 release concurrently.

**Comment by kamenov** [comment]
Had the same issue and solved it by reverting from `liquibase:3.6.2` to `liquibase:3.5.2` while still using `hibernate5/3.6`.
