### ISSUE TITLE
Run Diff changelog got error due to Hibernate 5.x has remove buildServiceRegistry from EntityManagerFactoryBuilderImpl

### ISSUE THREAD

**Issue by howie** [liquibase/liquibase-hibernate#135]
Hi

Here are my lib version.
hibernate-core 5.0.11.Final
liquibase-hibernate4 3.6
liquibase-core 3.5.3

I got NoSuchMethodError when I try to diff change log.

Unexpected error running Liquibase: org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.buildServiceRegistry()Lorg/hibernate/service/ServiceRegistry;

14:39:10.029 [main] ERROR liquibase - org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.buildServiceRegistry()Lorg/hibernate/service/ServiceRegistry;
java.lang.NoSuchMethodError: org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.buildServiceRegistry()Lorg/hibernate/service/ServiceRegistry;
	at liquibase.ext.hibernate.database.HibernateSpringDatabase.buildConfigurationFromScanning(HibernateSpringDatabase.java:245)
	at liquibase.ext.hibernate.database.HibernateSpringDatabase.buildConfiguration(HibernateSpringDatabase.java:55)
	at liquibase.ext.hibernate.database.HibernateDatabase.setConnection(HibernateDatabase.java:45)

	at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:131)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:85)
	at liquibase.integration.commandline.Main.createReferenceDatabaseFromCommandParams(Main.java:1283)
	at liquibase.integration.commandline.Main.doMigration(Main.java:996)
	at liquibase.integration.commandline.Main.run(Main.java:188)
	at liquibase.integration.commandline.Main.main(Main.java:103)

I check hibernate's source code . They have remove buildServiceRegistry from EntityManagerFactoryBuilderImpl. But HibernateSpringDatabase still use it .

![2016-11-18 2 48 00](https://cloud.githubusercontent.com/assets/2318485/20421721/c3708fb0-ada0-11e6-93ff-563e88d01fde.png)
![2016-11-18 2 48 08](https://cloud.githubusercontent.com/assets/2318485/20421722/c37b4e96-ada0-11e6-9020-8ae4b593bdd2.png)

**Comment by klmz** [comment]
You could use liquibase-hibernate5: https://mvnrepository.com/artifact/org.liquibase.ext/liquibase-hibernate5/3.6.

That comes with Hibernate 5.x support. (It resolved this same issues for me).
