### ISSUE TITLE
Adding databaseClass makes the liquibase:diff command not work, but the update works

### ISSUE THREAD

**Issue by Hervian** [liquibase/liquibase-hibernate#157]
Hi, thanks for a great plugin/extension. 

Overall it works great, but I am having a strange problem. I have extended the _PostgresDatabase_ class and overriden the _escapeObjectName_ method to make the generated table names case-insensitive (such as to avoid having double quotes in all queries.) To register my custom class I add the following line to liquibase.properties:

```java
databaseClass=liquibase.database.LiquibasePostgresDatabaseConfig
```

Now when I run ```mvn liquibase:update``` the table names are lower case as expected. **But the liquibase:diff command no longer works**, but throws and error. So to generate my changelog I must remove the databaseClass line.

This is the error from the maven output:

```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.5.3:diff (default-cli) on project data: Error setting up or running Liquibase: liquibase.exception.
DatabaseException: java.lang.RuntimeException: Cannot find database driver: Driver class was not specified and could not be determined from the url (hibernate:spring:dk.
test.data?dialect=org.hibernate.dialect.PostgreSQLDialect) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.liquibase:liquibase-maven-plugin:3.5.3:diff (default-cli) on project data: Error setti
ng up or running Liquibase: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: Driver class was not specified and could not
be determined from the url (hibernate:spring:dk.test.data?dialect=org.hibernate.dialect.PostgreSQLDialect)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:398)
        at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute(LiquibaseDatabaseDiff.java:146)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: Driver class was not specified and could not be determin
ed from the url (hibernate:spring:dk.test.data?dialect=org.hibernate.dialect.PostgreSQLDialect)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:127)
        at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask(LiquibaseDatabaseDiff.java:166)
        at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:394)
        ... 23 more
Caused by: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: Driver class was not specified and could not be determined from the url (hibernate:spring:dk.ma
nsipi.data?dialect=org.hibernate.dialect.PostgreSQLDialect)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:85)
        ... 25 more
Caused by: java.lang.RuntimeException: Cannot find database driver: Driver class was not specified and could not be determined from the url (hibernate:spring:dk.test.data?dialect=org.hibernate.dialec
t.PostgreSQLDialect)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:199)
        ... 27 more
```

This is my plugin section:

```
<plugin> 
	<groupId>org.liquibase</groupId>
	<artifactId>liquibase-maven-plugin</artifactId>
	<version>3.5.3</version>
	<configuration>
		<propertyFile>src/main/resources/liquibase/liquibase.properties</propertyFile>
		<changeLogFile>liquibase/liquibase-changelog-master.xml</changeLogFile>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.liquibase.ext</groupId>
			<artifactId>liquibase-hibernate5</artifactId>
			<version>3.6</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>4.3.9.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-jpa</artifactId>
			<version>1.11.4.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>5.3.5.Final</version>
		</dependency>
	</dependencies>
</plugin>
```

This is how my liquibase.properties file is configured:

```
url=jdbc:postgresql://localhost:5432/mydatabase
username=******
password=******
driver=org.postgresql.Driver
changeLogFile=src/main/resources/liquibase/liquibase-changeLog-master.xml
dialect=org.hibernate.dialect.PostgreSQLDialect
referenceUrl=hibernate:spring:dk.test.data?dialect=org.hibernate.dialect.PostgreSQLDialect
diffChangeLogFile=src/main/resources/liquibase/liquibase-diff-changeLog_tmp.xml
classpath: ./lib/postgresql-42.1.1.jar;
databaseClass=liquibase.database.LiquibasePostgresDatabaseConfig
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-463) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
HI - seems this has been fixed in liquibase-core some years ago. Please reopen the issue if it still persists.
