### ISSUE TITLE
liquibase-hibernate5 3.6 is incompatible with liquibase 3.6.x

### ISSUE THREAD

**Issue by haster** [liquibase/liquibase-hibernate#179]
liquibase-hibernate5 is compiled against liquibase-core 3.5.3
liquibase-core has changed its API between 3.5 and 3.6 in a way that is incompatible (see https://github.com/liquibase/liquibase/commit/6ddd845435163adf8897534fcfe25ad2b0963885), which means code compiled against liquibase 3.5 can not run against liquibase 3.6

This means running liquibase-hibernate5 3.6 with liquibase-core 3.6.x will result in runtime errors such as:

```
java.lang.NoSuchMethodError: liquibase.structure.core.UniqueConstraint.setTable(Lliquibase/structure/core/Table;)Lliquibase/structure/core/UniqueConstraint;
	at liquibase.ext.hibernate.snapshot.UniqueConstraintSnapshotGenerator.addTo(UniqueConstraintSnapshotGenerator.java:67)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:84)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:76)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:76)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:76)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:286)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:407)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:429)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:334)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:309)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:102)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:38)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:217)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:190)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:157)
```

**Comment by haster** [comment]
I also sent in a bug report with liquibase-core: https://liquibase.jira.com/browse/CORE-3206

**Comment by haster** [comment]
PR: https://github.com/liquibase/liquibase-hibernate/pull/180

**Comment by kevindaub** [comment]
Is there a target date that this will be merged to create a 3.6.2?

**Comment by haster** [comment]
As it seems there's been no activity on this project for the past two years I've been thinking about forking it and republishing updated artifacts under my own groupId.

**Comment by kevindaub** [comment]
If you are thinking of forking, maybe the owner of liquibase org or current maintainer @nvoxland could just give you the permissions? I would hate to see something  die on the vine.

**Comment by haster** [comment]
Yeah, I had the same thought last week and I found a forum post on liquibase forums where nathan asked for people who wanted to help out in a committer role. I send him an email offering to help out with liquibase-hibernate specifically. So far I have not received an answer but I'll wait a bit longer hoping he's just busy.

**Comment by robertoschwald** [comment]
@haster Any news on the forking? This project needs updates badly.

**Comment by pete-woods** [comment]
Agreed. @nvoxland please give @haster maintainer privileges on this repo, so he doesn't have to fork it permanently.

**Comment by benoitheinrich** [comment]
Not sure if people still have problems with this but I've got that plugin to work with liquibase 3.6.2 with not much issues.
I've got an example project here that actually provides fixes for other issues with that plugin:
https://github.com/benoitheinrich/liquibase-hibernate-bug

Feel free to have a look and see how I made it work.

**Comment by jameskleeh** [comment]
@nvoxland Unfortunately liquibase-hibernate5 is still incompatible with 3.6.3 due to https://github.com/liquibase/liquibase-hibernate/blob/master/src/main/java/liquibase/ext/hibernate/snapshot/PrimaryKeySnapshotGenerator.java not being changed
