### ISSUE TITLE
Liquibase cannot allocate memory exception when running in kubernetes

### ISSUE THREAD

**Issue by jain-anshul** [liquibase/liquibase-hibernate#190]
I am getting the following error when running schema migration through liquibase in kubernetes environment. I am using postgres database which is running in a separate container and my main app is running the schema migration from a different container. 
Though, when I tried to run it as a standalone app in my system, the migrations are carried out successfully. Is it due to any resource constraints of the container resources ? 

```
Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Cannot allocate memory
2018-10-11 11:39:27,776 ERROR: org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [file.class]: : Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Cannot allocate memory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.vmware.vcf.hawkeye.controller.inventory.manager.app.InventoryManagerApplication.main(InventoryManagerApplication.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: Cannot allocate memory
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:27)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:225)
	at liquibase.Liquibase.update(Liquibase.java:200)
	at liquibase.Liquibase.update(Liquibase.java:190)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1765)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	... 26 common frames omitted
Caused by: liquibase.exception.SetupException: Cannot allocate memory
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:367)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:274)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:221)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
	... 33 common frames omitted
Caused by: java.io.IOException: Cannot allocate memory
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at liquibase.util.FileUtil.unzip(FileUtil.java:85)
	at liquibase.resource.ClassLoaderResourceAccessor.list(ClassLoaderResourceAccessor.java:87)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.list(SpringLiquibase.java:143)
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:344)
	... 36 common frames omitted

```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-434) by [Unito](https://www.unito.io/learn-more)

**Comment by MWHunter** [comment]
Does the container have any memory overhead?  If you set xmx to the container size java has overhead from native stuff like this and it will crash.

**Comment by filipelautert** [comment]
Correct, this is due to constraints of the container resources - you will need to increase the container memory.
