### ISSUE TITLE
liquibase-hibernate5 3.7 Incompatible with liquibase 3.6.3

### ISSUE THREAD

**Issue by jameskleeh** [liquibase/liquibase-hibernate#198]
```
liquibase.structure.core.Index.setTable(Lliquibase/structure/core/Relation;)Lliquibase/structure/core/Index;
java.lang.NoSuchMethodError: liquibase.structure.core.Index.setTable(Lliquibase/structure/core/Relation;)Lliquibase/structure/core/Index;
	at liquibase.ext.hibernate.snapshot.PrimaryKeySnapshotGenerator.addTo(PrimaryKeySnapshotGenerator.java:75)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:84)
```

Seems like https://github.com/liquibase/liquibase-hibernate/issues/179 was not implemented completely

**Comment by marcioluis** [comment]
**Same error using liquibase/liquibase-plugin 3.7.0**

Caused by: java.lang.NoSuchMethodError: liquibase.structure.core.Index.setTable(Lliquibase/structure/core/Relation;)Lliquibase/structure/core/Index;
    at liquibase.ext.hibernate.snapshot.PrimaryKeySnapshotGenerator.addTo (PrimaryKeySnapshotGenerator.java:75)
    at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot (HibernateSnapshotGenerator.java:84)
    at liquibase.snapshot.SnapshotGeneratorChain.snapshot (SnapshotGeneratorChain.java:49)
    at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot (HibernateSnapshotGenerator.java:76)
    at liquibase.snapshot.SnapshotGeneratorChain.snapshot (SnapshotGeneratorChain.java:49)
    at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot (HibernateSnapshotGenerator.java:76)
    at liquibase.snapshot.SnapshotGeneratorChain.snapshot (SnapshotGeneratorChain.java:49)
    at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot (HibernateSnapshotGenerator.java:76)
    at liquibase.snapshot.SnapshotGeneratorChain.snapshot (SnapshotGeneratorChain.java:49)
    at liquibase.snapshot.DatabaseSnapshot.include (DatabaseSnapshot.java:315)
    at liquibase.snapshot.DatabaseSnapshot.replaceObject (DatabaseSnapshot.java:436)
    at liquibase.snapshot.DatabaseSnapshot.replaceObject (DatabaseSnapshot.java:458)
    at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects (DatabaseSnapshot.java:363)
    at liquibase.snapshot.DatabaseSnapshot.include (DatabaseSnapshot.java:338)
    at liquibase.snapshot.DatabaseSnapshot.init (DatabaseSnapshot.java:106)
    at liquibase.snapshot.DatabaseSnapshot.<init> (DatabaseSnapshot.java:59)
    at liquibase.snapshot.JdbcDatabaseSnapshot.<init> (JdbcDatabaseSnapshot.java:39)
    at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot (SnapshotGeneratorFactory.java:217)
    at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot (SnapshotGeneratorFactory.java:190)
    at liquibase.command.core.DiffCommand.createReferenceSnapshot (DiffCommand.java:221)
    at liquibase.command.core.DiffCommand.createDiffResult (DiffCommand.java:143)
    at liquibase.command.core.DiffToChangeLogCommand.run (DiffToChangeLogCommand.java:51)
    at liquibase.command.AbstractCommand.execute (AbstractCommand.java:19)
    at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog (CommandLineUtils.java:237)
    at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog (CommandLineUtils.java:212)
    at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask (LiquibaseDatabaseDiff.java:178)
    at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute (AbstractLiquibaseMojo.java:371)
    at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute (LiquibaseDatabaseDiff.java:137)

**Comment by tripleplayj** [comment]
Is there any update with this? I'm having a similar compatibility problem.

**Comment by DanielFran** [comment]
@nvoxland There is any expectation to fix this issue?
Actually since 3.6.3 (and now 3.7.0) we cannot use this plugin...
Thanks

**Comment by armin-vcg** [comment]
This is a showstopper for some of us. If I have time, I will dive in and see if a solution presents itself. In the meantime, Liquibase has disqualified itself from our database maintenance strategy.

**Comment by armin-vcg** [comment]
Thank you. Initial testing indicates this issue does indeed appear to be resolved.

**Comment by Migsi** [comment]
@armin-vcg what where you able to conclude in your tests? I'm currently running into similar problems...

**Comment by armin-vcg** [comment]
> @armin-vcg what where you able to conclude in your tests? I'm currently running into similar problems...

Fixed it by upgrading the liquibase-hibernate5 extension to v 3.8 ... seems to work as advertised
