### ISSUE TITLE
Errors while trying to generate diff on hibernate schema

### ISSUE THREAD

**Issue by rgordeev** [liquibase/liquibase-hibernate#255]
Gradle liquibase plugin config

```
ext {
    runList = "diffJpa"
    diffChangelogFile = "src/main/resources/liquibase/changelog/" + new Date().format("yyyyMMddHHmmss") + "_changelog.xml"
}

liquibase {
    activities {
        diffJpa {
            driver "org.postgresql.Driver"
            url "jdbc:postgresql://localhost:5432/service"
            username "service"
            password "service"
            changeLogFile project.ext.diffChangelogFile
            referenceUrl "hibernate:spring:com.service.domain?dialect=org.hibernate.dialect.PostgreSQL10Dialect&hibernate.enhanced_id=true&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
            logLevel "debug"
            classpath "$buildDir/classes/java/main"
        }
    }

    runList = project.ext.runList
}
```

Gradle dependencies 

```
    implementation "org.liquibase:liquibase-core:3.9.0"
    liquibaseRuntime "org.liquibase:liquibase-core:3.9.0"
    liquibaseRuntime "org.liquibase.ext:liquibase-hibernate5:3.9.0"
    liquibaseRuntime sourceSets.main.compileClasspath
```

Task to execute

```
./gradlew liquibaseDiff 
```

Got the error

```
> Task :liquibaseDiff
liquibase-plugin: Running the 'diffJpa' activity...
15:32:15.935 INFO  [liquibase.integration.commandline.Main]: Starting Liquibase at Сб, 04 июл 2020 15:32:15 MSK (version 3.9.0 #11 built at Thu May 14 04:03:56 UTC 2020)
15:32:16.632 INFO  [liquibase.integration.commandline.Main]: No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
15:32:16.633 INFO  [liquibase.integration.commandline.Main]: Liquibase Community 3.9.0 by Datical
15:32:16.741 INFO  [liquibase.ext.hibernate.database.HibernateDatabase]: Reading hibernate configuration hibernate:spring:com.service.domain?dialect=org.hibernate.dialect.PostgreSQL10Dialect&hibernate.enhanced_id=true&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
15:32:16.809 INFO  [liquibase.ext.hibernate.database.HibernateDatabase]: Found package com.service.domain
15:32:35.321 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: String index out of range: 0
liquibase.exception.DatabaseException: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:132)
        at liquibase.integration.commandline.Main.createReferenceDatabaseFromCommandParams(Main.java:1904)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1411)
        at liquibase.integration.commandline.Main.run(Main.java:302)
        at liquibase.integration.commandline.Main.main(Main.java:159)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at org.jboss.jandex.GenericSignatureParser.parseReferenceType(GenericSignatureParser.java:433)
        at org.jboss.jandex.GenericSignatureParser.parseFieldSignature(GenericSignatureParser.java:272)
        at org.jboss.jandex.Indexer.parseFieldSignature(Indexer.java:1109)
        at org.jboss.jandex.Indexer.applySignatures(Indexer.java:1101)
        at org.jboss.jandex.Indexer.index(Indexer.java:1601)
        at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.toClassDescriptor(ClassFileArchiveEntryHandler.java:64)
        at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.handleEntry(ClassFileArchiveEntryHandler.java:52)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:143)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.processDirectory(ExplodedArchiveDescriptor.java:118)
        at org.hibernate.boot.archive.internal.ExplodedArchiveDescriptor.visitArchive(ExplodedArchiveDescriptor.java:54)
        at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:48)
        at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:76)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:98)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:254)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:168)
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:32)
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:89)
        at liquibase.ext.hibernate.database.HibernateSpringPackageDatabase.createEntityManagerFactoryBuilder(HibernateSpringPackageDatabase.java:98)
        at liquibase.ext.hibernate.database.HibernateEjb3Database.buildMetadataFromPath(HibernateEjb3Database.java:56)
        at liquibase.ext.hibernate.database.HibernateDatabase.buildMetadata(HibernateDatabase.java:145)
        at liquibase.ext.hibernate.database.HibernateDatabase.setConnection(HibernateDatabase.java:85)
        at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:129)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:149)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:97)
        ... 4 common frames omitted

```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-405) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Could you please try again in a more recent version of liquibase as a lot has been fixed over the years. Please reopen the issue if it still persists.
