### ISSUE TITLE
Regression with Hibernate 5.4.28.Final onwards

### ISSUE THREAD

**Issue by f4lco** [liquibase/liquibase-hibernate#342]
Hi,

I can't use liquibase-hibernate with Hibernate 5.4.28.Final. Starting at Hibernate 5.4.14, I tested all patch releases up to 5.4.28, and 5.4.28 is the version to expose this behavior. During the diff, I get below exception, and the diff output suggests do drop a couple of foreign key constraints. Latter is not logical, because the Hibernate entity definitions and the database stayed the same throughout the entire process.

In summary, my tests results have been:

* Hibernate 5.4.14 up to 5.4.27: :white_check_mark:
* Hibernate 5.4.28 up to 5.4.32: :x:

To my conclusion, Hibernate must have changed some sort of API in the 5.4.28 release, and liquibase-hibernate cannot cope with that yet.

```
12:43:35.015 [main] WARN org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator - HHH000181: No appropriate connection provider encountered, assuming application will be supplying connections
12:43:35.017 [main] WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator - HHH000342: Could not obtain connection to query metadata
java.lang.UnsupportedOperationException: The application must supply JDBC connections
	at org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl.getConnection(UserSuppliedConnectionProviderImpl.java:44)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:176)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1224)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1255)
	at liquibase.ext.hibernate.database.HibernateEjb3Database.buildMetadataFromPath(HibernateEjb3Database.java:59)
	at liquibase.ext.hibernate.database.HibernateDatabase.buildMetadata(HibernateDatabase.java:143)
	at liquibase.ext.hibernate.database.HibernateDatabase.setConnection(HibernateDatabase.java:83)
	at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:121)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:90)
	at liquibase.integration.commandline.Main.createReferenceDatabaseFromCommandParams(Main.java:2193)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1601)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:399)
	at liquibase.Scope.lambda$child$0(Scope.java:166)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:144)
	at liquibase.integration.commandline.Main$1.run(Main.java:398)
	at liquibase.integration.commandline.Main$1.run(Main.java:222)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.Main.run(Main.java:222)
	at liquibase.integration.commandline.Main.main(Main.java:165)
```

As a workaround, I maintain the following dependency constraint in my `build.gradle.kts`;

```kotlin
configurations {
    "liquibaseRuntime" {
        resolutionStrategy {
            force("org.hibernate:hibernate-core:5.4.14.Final")
        }
    }
}
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1941) by [Unito](https://www.unito.io)

**Comment by mehdirahimi** [comment]
I still have the same problem with Spring-Boot 3.1.3 and liquibase-hibernate6!

**Comment by filipelautert** [comment]
Hi - this is an issue related to your url connection. The error message has been improved in latest versions, please try again and reopen the issue if the problem still persists.
