### ISSUE TITLE
Support for hibernate 6.2

### ISSUE THREAD

**Issue by razubuddy** [liquibase/liquibase-hibernate#495]
Hibernate 6.2 changed base class for generators, now it is `org.hibernate.id.Generator` instead of `org.hibernate.id.IdentifierGenerator`. This change generates `ClassCastException` in current imnplementation:

```
java.lang.ClassCastException: class org.hibernate.id.IdentityGenerator cannot be cast to class org.hibernate.id.IdentifierGenerator (org.hibernate.id.IdentityGenerator and org.hibernate.id.IdentifierGenerator are in unnamed module of loader 'app')
        at org.hibernate.mapping.KeyValue.createIdentifierGenerator(KeyValue.java:58)
        at liquibase.ext.hibernate.snapshot.TableSnapshotGenerator.addTo(TableSnapshotGenerator.java:84)
        at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:82)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:74)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:313)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:106)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:214)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:187)
        at liquibase.command.core.DiffCommandStep.generateDatabaseShapshot(DiffCommandStep.java:203)
        at liquibase.command.core.DiffCommandStep.createReferenceSnapshot(DiffCommandStep.java:190)
        at liquibase.command.core.DiffCommandStep.createDiffResult(DiffCommandStep.java:113)
        at liquibase.command.core.DiffCommandStep.run(DiffCommandStep.java:89)
        at liquibase.command.CommandScope.execute(CommandScope.java:212)
        ...
```

**Comment by bazsoja** [comment]
We have the same problem. Is there any update on this?

**Comment by bazsoja** [comment]
Thank you for the feedback!

**Comment by xintellion** [comment]
The release notes say it was included but it is still 4.23.0 still uses hibernate 6.1.* any plans for 4.23.1?

**Comment by matthiasstrauch** [comment]
Running 4.23.0 and having the same issue with the @UuidGenerator annotation:
`liquibase.exception.CommandExecutionException: java.lang.ClassCastException: class org.hibernate.id.uuid.UuidGenerator cannot be cast to class org.hibernate.id.IdentifierGenerator (org.hibernate.id.uuid.UuidGenerator and org.hibernate.id.IdentifierGenerator are in unnamed module of loader 'app')`

**Comment by Bert-R** [comment]
I've been debugging this and in my view, it's an issue in Hibernate. I've reported it as [HHH-16912](https://hibernate.atlassian.net/browse/HHH-16912).

**Comment by Bert-R** [comment]
@nvoxland @filipelautert Can someone from the Liquibase Hibernate team look at the feedback that the Hibernate team provided on [HHH-16912](https://hibernate.atlassian.net/browse/HHH-16912)?

**Comment by filipelautert** [comment]
@Bert-R thanks for the ping. I'll fix the cast on Liquibase side for the next release and will link the PR here so we can get it tested.

**Comment by filipelautert** [comment]
PR https://github.com/liquibase/liquibase-hibernate/pull/508 should fix it - please fell free to test it.

**Comment by Bert-R** [comment]
@filipelautert Thanks for the very quick follow up!
I don't know how to test it. The procedure described on the PR is based on Maven, but I'm using Gradle.
However, I'm confident that will work, as I implemented the same fix two weeks ago, while debugging the issue. At that time, I didn't dare to create a PR as that would break compatibility with Hibernate 6.0.2 and 6.1.7.

You've removed these from the texting matrix, so you apparently accept breaking that compatibility. In that case, I'd suggest to remove the testing matrix, to prevent manual maintenance effort. Dependabot does not update that value, so you always need to change it manually. That is why the incompatibility of 6.2 could go unnoticed.

**Comment by Bert-R** [comment]
That makes sense.

The suggestion on  [HHH-16912](https://hibernate.atlassian.net/browse/HHH-16912) was slightly different from what you implemented:

> Now, on the other hand, on the Liquibase side, and please bear with me, because I don’t know anything about that code _at all_, but it appears that Liquibase only supports `TableGenerator`, and not `SequenceStyleGenerator` in table mode, which is a quite usual type of table generation since a long time.

That might be a way to implement a new generator that's compatible with all 6.x versions.

**Comment by Bert-R** [comment]
The intermediate solution (upgrade to 6.2.7) works for me. Thanks for that!

**Comment by filipelautert** [comment]
Thanks for the feedback! I'm still thinking on how to use 6.2 apis breaking backwards compatibility - thus I"m holding https://github.com/liquibase/liquibase-hibernate/pull/508 a bit. 
Anyway this one can be closed as fixed by https://github.com/hibernate/hibernate-orm/pull/7023 🎉
