### ISSUE TITLE
Error running Liquibase-Hibernate with Spring Data JPA (and no persistence.xml file)

### ISSUE THREAD

**Issue by jdubois** [liquibase/liquibase-hibernate#68]
I'm trying to make Liquibase-Hibernate work with [JHipster](http://jhipster.github.io/), see issue [#754](https://github.com/jhipster/generator-jhipster/issues/754)

Here is my configuration:

```
        <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <changeLogFile>classpath:config/liquibase/master.xml</changeLogFile>
                    <url>hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.MySQLInnoDBDialect</url>
                    <referenceDriver>com.mysql.jdbc.Driver</referenceDriver>
                    <referenceUrl>jdbc:mysql://localhost:3306/jhipster</referenceUrl>
                    <referenceDefaultSchemaName>jhipster</referenceDefaultSchemaName>
                    <referenceUsername>root</referenceUsername>
                    <referencePassword></referencePassword>
                    <verbose>true</verbose>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate4.2</artifactId>
                        <version>3.4</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-data-jpa</artifactId>
                        <version>${spring-boot.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

When running "mvn liquibase:diff -X", I get:

```
[INFO] ------------------------------------------------------------------------
[INFO] Settings
----------------------------
[INFO]     driver: null
[INFO]     url: hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.MySQLInnoDBDialect
[INFO]     username: null
[INFO]     password: *****
[INFO]     use empty password: false
[INFO]     properties file: null
[INFO]     properties file will override? false
[INFO]     prompt on non-local database? true
[INFO]     clear checksums? false
[INFO]     changeLogFile: classpath:config/liquibase/master.xml
[INFO]     context(s): null
[INFO]     label(s): null
[INFO]     referenceDriver: com.mysql.jdbc.Driver
[INFO]     referenceUrl: jdbc:mysql://localhost:3306/jhipster
[INFO]     referenceUsername: root
[INFO]     referencePassword: null
[INFO]     referenceDefaultSchema: jhipster
[INFO]     diffChangeLogFile: null
[INFO] ------------------------------------------------------------------------
INFO 18/11/14 16:26: liquibase-hibernate: Reading hibernate configuration hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.MySQLInnoDBDialect
INFO 18/11/14 16:26: liquibase-hibernate: Found package com.mycompany.myapp.domain
INFO 18/11/14 16:26: liquibase-hibernate: Found dialect org.hibernate.dialect.MySQLInnoDBDialect
[DEBUG] Resolved location pattern [classpath*:com/mycompany/myapp/domain/**/*.class] to resources []
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.590 s
[INFO] Finished at: 2014-11-18T16:26:56+01:00
[INFO] Final Memory: 20M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.3.0:diff (default-cli) on project jhipster: Error setting up or running Liquibase: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL: class path resource [] cannot be resolved to URL because it does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.liquibase:liquibase-maven-plugin:3.3.0:diff (default-cli) on project jhipster: Error setting up or running Liquibase: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error setting up or running Liquibase: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
    at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:373)
    at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute(LiquibaseDatabaseDiff.java:129)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: liquibase.exception.DatabaseException: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
    at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:54)
    at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:321)
    ... 22 more
Caused by: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL
    at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:591)
    at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.preparePersistenceUnitInfos(DefaultPersistenceUnitManager.java:443)
    at liquibase.ext.hibernate.database.HibernateSpringDatabase.buildConfigurationFromScanning(HibernateSpringDatabase.java:226)
    at liquibase.ext.hibernate.database.HibernateSpringDatabase.buildConfiguration(HibernateSpringDatabase.java:54)
    at liquibase.ext.hibernate.database.HibernateDatabase.setConnection(HibernateDatabase.java:45)
    at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:123)
    at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:143)
    at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:45)
    ... 23 more
Caused by: java.io.FileNotFoundException: class path resource [] cannot be resolved to URL because it does not exist
    at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
    at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl(DefaultPersistenceUnitManager.java:588)
    ... 30 more
```

I think this is because I don't have a persistence.xml file with Spring Data JPA.

**Comment by jgribonvald** [comment]
It's working for me with these properties 
```
changeLogFile: src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml
diffChangeLogFile: src/main/resources/config/liquibase/changelog/20150105150500_main_schema.xml
driver: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/mybase
defaultSchema: mybase
username: root
password: root
referenceUrl: hibernate:spring:my.app.domain?dialect=my.app.utils.MySQL5InnoDBCompressedDialect
verbose: true
dropFirst: false
logging: debug

```

and my pom definition 

```
<plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>3.4.0-SNAPSHOT</version>
                <dependencies>
                    <dependency>
                        <groupId>my.app</groupId>
                        <artifactId>myapp</artifactId>
                        <version>0.0.1-SNAPSHOT</version>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-core</artifactId>
                        <version>3.4.0-SNAPSHOT</version>
                        <exclusions>
                            <exclusion>
                                <artifactId>jetty-servlet</artifactId>
                                <groupId>org.eclipse.jetty</groupId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate4</artifactId>
                        <version>3.5-SNAPSHOT</version>
                        <exclusions>
                            <exclusion>
                                <artifactId>hibernate-jpa-2.0-api</artifactId>
                                <groupId>org.hibernate.javax.persistence</groupId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate4</artifactId>
                        <version>${liquibase-hibernate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-context-support</artifactId>
                        <version>${spring.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-orm</artifactId>
                        <version>${spring.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>xml-apis</groupId>
                        <artifactId>xml-apis</artifactId>
                        <version>1.4.01</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <propertyFile>src/main/resources/config/liquibase/liquibase.properties.generation</propertyFile>
                    <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                </configuration>
            </plugin>
```
Like you can see i injected as a dependency my project, but it was needed only for my custom dialect ( but maybe not only, this could be usefull for JPA object scanning from url)

**Comment by pkraeutli** [comment]
Thanks, now my set up almost works! I am still running in this NPE, though:

```
Caused by: java.lang.NullPointerException
	at liquibase.ext.hibernate.snapshot.PrimaryKeySnapshotGenerator.addTo(PrimaryKeySnapshotGenerator.java:59)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:80)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:163)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:241)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:263)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:195)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:177)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:60)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:37)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:25)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:126)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:119)
	at liquibase.command.DiffCommand.createReferenceSnapshot(DiffCommand.java:190)
	at liquibase.command.DiffCommand.createDiffResult(DiffCommand.java:140)
	at liquibase.command.DiffCommand.run(DiffCommand.java:132)
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
	... 32 more
```

But this is probably not related to this issue anymore. Should I open another issue? Or do you think this is because of some misconfiguration?

Here is my current setup:

```xml
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>3.4.0-SNAPSHOT</version>
                <configuration>
                    <propertyFile>src/main/resources/config/liquibase/liquibase.properties.generation</propertyFile>
                    <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-core</artifactId>
                        <version>3.4.0-SNAPSHOT</version>
                        <exclusions>
                            <exclusion>
                                <artifactId>jetty-servlet</artifactId>
                                <groupId>org.eclipse.jetty</groupId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate4</artifactId>
                        <version>3.5-SNAPSHOT</version>
                        <exclusions>
                            <exclusion>
                                <artifactId>hibernate-jpa-2.0-api</artifactId>
                                <groupId>org.hibernate.javax.persistence</groupId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate4</artifactId>
                        <version>3.5-SNAPSHOT</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-context-support</artifactId>
                        <version>${spring.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-orm</artifactId>
                        <version>${spring.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>xml-apis</groupId>
                        <artifactId>xml-apis</artifactId>
                        <version>1.4.01</version>
                    </dependency>
                </dependencies>
            </plugin>
```

```
changeLogFile: src/main/resources/config/liquibase/master.xml
#diffChangeLogFile: src/main/resources/config/liquibase/changelog/20150105150500_main_schema.xml
driver: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/project_template
defaultSchema: project_template
username: root
password: root
referenceUrl: hibernate:spring:app.model?dialect=org.hibernate.dialect.MySQL5Dialect
verbose: true
dropFirst: false
logging: debug
```

**Comment by jdubois** [comment]
Yes, you are hitting this issue: https://github.com/liquibase/liquibase-hibernate/issues/72
And I have the same !

**Comment by nvoxland** [comment]
Issue https://github.com/liquibase/liquibase-hibernate/issues/72 is fixed now in the hibernate4.2 branch.
