### ISSUE TITLE
NPE on PrimaryKeySnapshotGenerator

### ISSUE THREAD

**Issue by jdubois** [liquibase/liquibase-hibernate#72]
This issue comes from https://github.com/jhipster/generator-jhipster/issues/754#issuecomment-68447462

I am using liquibase 3.3.2-SNAPSHOT, and when doing a "mvn compile liquibase:diff" I have the following stacktrace.

In order to reproduce this, you can get my project here:
https://www.dropbox.com/s/33rskcw6y92chii/tmp-mysql.zip?dl=0
It is using MySQL, configuration is in the pom.xml (for the Maven Plugin) and in src/main/resources/config/application-dev.yml (for running the app). You can run the app by typing "mvn spring-boot:run".
And of course you will get the exception when typing "mvn compile liquibase:diff -X"
-> please note that we have another error if we don't call "compile" first, which is another strange issue...

```
Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:373)
	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute(LiquibaseDatabaseDiff.java:145)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:123)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:100)
	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask(LiquibaseDatabaseDiff.java:176)
	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:369)
	... 22 more
Caused by: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13)
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:121)
	... 25 more
Caused by: java.lang.NullPointerException
	at liquibase.ext.hibernate.snapshot.PrimaryKeySnapshotGenerator.addTo(PrimaryKeySnapshotGenerator.java:60)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:80)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.ext.hibernate.snapshot.HibernateSnapshotGenerator.snapshot(HibernateSnapshotGenerator.java:72)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:163)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:241)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:263)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:195)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:177)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:60)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:37)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:25)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:126)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:119)
	at liquibase.command.DiffCommand.createReferenceSnapshot(DiffCommand.java:190)
	at liquibase.command.DiffCommand.createDiffResult(DiffCommand.java:140)
	at liquibase.command.DiffToChangeLogCommand.run(DiffToChangeLogCommand.java:51)
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
	... 26 more
```

**Comment by dolavb** [comment]
I have the same issue. It happens when the primary key is made of several columns and not generated by an ID annotation. One of the example I have in my code looks like this:

```
@OneToMany(cascade=CascadeType.ALL)
@MapKeyClass(Key.class)
private Map<Key, Enitty> entities; 
```

In this case I end up with a primary key named `PRIMARY` in MySQL.  However the named in the hibernate primary key is set to null. I haven't confirmed in the hibernate generated DDL, but I believe this name is RDBMS specific and is set when no name is specified when creating a PK. So it could be something else for other database.

I got it working by adding something like this
```
if(hbnPrimaryKeyName==null){
   hbnPrimaryKeyName = "PRIMARY";
}
```

in the addTo method of the PrimaryKeySnapshotGenerator. This is not a fix but I believe it helps to pin points the source of error to the piece of code that covers the cases of truncated key names.

**Comment by nvoxland** [comment]
Thanks for the test cases, that helps. The main problem was that I had fixed the issue in liquibase-hibernate/master but you are using the 4.2 branch. Since you are running against Hibernate 4.3.6 you can just use the liquibase-hibernate artifact. That version supports 4.3+  Is there a reason you were using liquibase-hibernate4.2?

I did merge master into the 4.2 branch and push the changes up which should fix it on both branches now.
